# Cargamos DF y Transformamos

In [1]:
# Librerias
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
# Nos conectamos a Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
# Cargamos CSV
df = pd.read_csv("/content/drive/Shareddrives/Data_TFM/orders_2023_22_21.csv", sep="	", decimal=".", na_values=['(null)'], low_memory=False)
df.head()

,unique_venue_id,year,month,content_channel_name,online_order_segment,payment_method_name,saas_product,gross_orders,gross_item_eur_amount_ttv,gross_aov,gross_revenue_eur,gross_take_rate,cancelled_orders,cancelled_item_eur_amount_ttv,cancelled_aov,cancelled_revenue_eur,cancelled_take_rate
0,1.200002e+10,2022.0,11.0,Marketplace,4.Loyal,Pay at venue,tw_pro,4,120.00,30.000000,0.00,0.000000,1.0,30.00,30.000000,0.00,0.000000
1,1.100039e+10,2022.0,11.0,Marketplace,4.Loyal,Pay at venue,tw_connect,561,16025.01,28.565080,0.00,0.000000,47.0,1298.00,27.617021,0.00,0.000000
2,1.100038e+10,2022.0,11.0,Widget,4.Loyal,iDeal_intent,tw_connect,18,872.00,48.444444,17.44,0.020000,2.0,113.00,56.500000,2.26,0.020000
3,1.100040e+10,2022.0,10.0,Marketplace,4.Loyal,PayPal,tw_connect,12,622.30,51.858333,12.46,0.020022,1.0,145.95,145.950000,2.92,0.020007
4,1.100033e+10,2022.0,11.0,Widget,4.Loyal,PayPal,tw_connect,2,116.24,58.120000,2.34,0.020131,NaN,NaN,NaN,NaN,NaN

In [14]:
df["cancelled_take_rate"].describe()

count    1.763025e+06
mean     1.358152e-01
std      1.600124e-01
min      0.000000e+00
25%      0.000000e+00
50%      2.000000e-02
75%      3.499935e-01
max      5.000000e-01
Name: cancelled_take_rate, dtype: float64

In [9]:
df.isnull().sum()

unique_venue_id                     1468
year                                   0
month                                  0
content_channel_name                   0
online_order_segment                   0
payment_method_name                60342
saas_product                           0
gross_orders                           0
gross_item_eur_amount_ttv              0
gross_aov                              0
gross_revenue_eur                      0
gross_take_rate                    62432
cancelled_orders                 3257588
cancelled_item_eur_amount_ttv    3257588
cancelled_aov                    3257588
cancelled_revenue_eur            3257588
cancelled_take_rate              3258727
dtype: int64

In [10]:
df.shape

(5021752, 17)

In [11]:
3257588/5021752

0.6486955150314073

In [ ]:
df['unique_venue_id'] = df['unique_venue_id'].astype(str)

In [ ]:
df[(df.unique_venue_id == '11000371533')]

In [ ]:
#(null) to nan
df.replace('(null)', np.nan, inplace=True)

In [ ]:
# Información del Dataset
df.info()

In [ ]:
# Unique Venue ID
df.unique_venue_id.nunique()

In [ ]:
df.isna().sum()

In [ ]:
df.loc[df.unique_venue_id== 12000000439].sort_values(by=['month'],ascending=False)

In [16]:
# Cargamos CSV
df_venues = pd.read_csv("/content/drive/Shareddrives/Data_TFM/venues_2023_22_21.csv", sep="	", decimal=".", na_values=['(null)'], low_memory=False)
df_venues.head()

,date_day,unique_venue_id,created,venue_status,venue_active_from,original_marketplace_venue_type_name,country_code,tier,saas_product,first_live_date,...,plan_active_from,plan_active_to,prepay,prepaid_until_to,discount,plan_discount_end_date,bill_every,plan_name,plan_fee_eur,is_zero_commission_plan
0,2021-07-01,11000000016,2008-03-25 12:47:09,DISABLED,NaN,Hotel Spa,GB,NaN,tw_connect,2009-07-20 00:00:00,...,2021-04-14 13:31:29,2999-12-31 00:00:00,0,NaN,0,NaN,1.0,Entry,16.65,False
1,2021-08-01,11000000016,2008-03-25 12:47:09,DISABLED,NaN,Hotel Spa,GB,NaN,tw_connect,2009-07-20 00:00:00,...,2021-04-14 13:31:29,2999-12-31 00:00:00,0,NaN,0,NaN,1.0,Entry,16.65,False
2,2021-09-01,11000000016,2008-03-25 12:47:09,DISABLED,NaN,Hotel Spa,GB,NaN,tw_connect,2009-07-20 00:00:00,...,2021-04-14 13:31:29,2999-12-31 00:00:00,0,NaN,0,NaN,1.0,Entry,16.65,False
3,2021-10-01,11000000016,2008-03-25 12:47:09,DISABLED,NaN,Hotel Spa,GB,NaN,tw_connect,2009-07-20 00:00:00,...,2021-04-14 13:31:29,2999-12-31 00:00:00,0,NaN,0,NaN,1.0,Entry,16.65,False
4,2021-11-01,11000000016,2008-03-25 12:47:09,DISABLED,NaN,Hotel Spa,GB,NaN,tw_connect,2009-07-20 00:00:00,...,2021-04-14 13:31:29,2999-12-31 00:00:00,0,NaN,0,NaN,1.0,Entry,16.65,False

In [ ]:
# Convertimos (null) en NaN
df_venues.replace("(null)", np.nan,inplace=True)

In [ ]:
#Transformamos la variable a formato fecha
df_venues['disabled_date'] = pd.to_datetime(df_venues['disabled_date'])
df_venues['first_live_date'] = pd.to_datetime(df_venues['first_live_date'])
df_venues['latest_live_date'] = pd.to_datetime(df_venues['latest_live_date'])

In [ ]:
# Eliminar todos los registros que tienen valores NaN en latest_live_date, ya que parece ser un error en los datos
df_venues.dropna(subset=['latest_live_date'], inplace=True)

In [ ]:
# Si Disabled_Date > Latest_Live_Date por 2 meses, consideramos churn es 1, si no, churn es 0
dos_meses = df_venues['latest_live_date'] + pd.DateOffset(months=3)
df_venues['churn'] = np.where(df_venues['disabled_date'] > dos_meses, 1, 0)

In [ ]:
df_venues.churn.value_counts(normalize=True) * 100

# Merge

https://stackoverflow.com/questions/48304927/cleanly-combine-year-and-month-columns-to-single-date-column-with-pandas

In [ ]:
# Convertimos date de Orders a formato
df['date_day_r'] = pd.to_datetime(df[['year', 'month']].assign(day=1))
df['date_day_r'] = pd.to_datetime(df['date_day_r']).dt.to_period('M')
df.head()

In [ ]:
df_venues['date_day'] = pd.to_datetime(df_venues['date_day'])
df_venues["date_day_r"] = df_venues['date_day'] - dt.timedelta(weeks=4)
df_venues['date_day_r'] = pd.to_datetime(df_venues['date_day_r']).dt.to_period('M')
df_venues.head()

In [ ]:
#result = pd.merge(df, df_venues, on=["unique_venue_id", "date_day_r"])
result = pd.merge(df, df_venues,  how='left', left_on=['unique_venue_id','date_day_r'], right_on = ['unique_venue_id','date_day_r'])
result.head()

In [ ]:
result.shape

# Creación de Nuevas Variables

Orders:
* Gross Online Orders: All online orders placed on the marketplace **OK**
* Net Online Orders: Gross Online Orders - Cancelled Online Orders **TBD**
* Online Order Segmentation: Newbie, Referral, Explorer, Loyal **OK**
* Direct Appointments: Appointments added directly in the SaaS by the salon **OK**
* Prepay at Venue: If the order was prepay at the Venue or not. **TBD**
* Prepay Method: The method how prepay was paid. **OK**

Cancellations:
* Order Cancellation Rate: Cancelled Online Orders / Created Online Orders **TBD**
* Revenue Cancellation Rate: Cancelled Order Revenue / Order Revenue **TBD**

Order Revenue:
* Gross Order Revenue: This is the revenue we make of the Marketplace **OK**
* Net Order Revenue: Gross Order Revenue - Cancelled Revenue **TBD**
* TTV: Total Transaction Value **TBD**
* AOV: Average Order Value **TBD**
* Take Rate: Net Order Revenue / Net TTV **TBD**

**Orders:**
* Net Online Orders: Gross Online Orders - Cancelled Online Orders **TBD**
* Prepay at Venue: If the order was prepay at the Venue or not. **TBD**

**Cancellations:**
* Order Cancellation Rate: Cancelled Online Orders / Created Online Orders **TBD**
* Revenue Cancellation Rate: Cancelled Order Revenue / Order Revenue **TBD**

**Order Revenue:**
* Net Order Revenue: Gross Order Revenue - Cancelled Revenue **TBD**
* TTV: Total Transaction Value **TBD**
* AOV: Average Order Value **TBD**
* Take Rate: Net Order Revenue / Net TTV **TBD**

In [ ]:
# Convert variables to numeric
numeric_cols = ['gross_orders', 'cancelled_orders']
result[numeric_cols] = result[numeric_cols].apply(pd.to_numeric)
# Fill NA values with 0 in column 'A'
result['cancelled_orders'].fillna(0, inplace=True)
# Value >0
result = result.loc[result['gross_orders'] >= 0]
result = result.loc[result['cancelled_orders'] >= 0]
# Net Online Orders
result['net_online_orders'] = result['gross_orders'] - result['cancelled_orders']
result.head()

In [ ]:
df.payment_method_name.unique()

In [ ]:
# Create the new column 'new_column' based on the condition
result['pay_at_venue'] = result['payment_method_name'].apply(lambda x: 1 if x == 'Pay at venue' else 0)
result.head()

In [ ]:
# Order Cancellation Rate
result['cancellation_rate'] = result['cancelled_orders'] / result['gross_orders']
result.head(5)

In [ ]:
blabla = result.loc[result.unique_venue_id== 11000322129].sort_values(by=['month'],ascending=False)
blabla

In [ ]:
blabla[["gross_orders","cancelled_orders","net_online_orders"]]

In [ ]:
# Convert variables to numeric
numeric_cols = ['gross_revenue_eur', 'cancelled_revenue_eur']
result[numeric_cols] = result[numeric_cols].apply(pd.to_numeric)
# Fill NA values with 0 in column 'A'
result['cancelled_revenue_eur'].fillna(0, inplace=True)
# Value >0
result = result.loc[result['gross_revenue_eur'] >= 0]
result = result.loc[result['cancelled_revenue_eur'] >= 0]
# Net Revenue
result['net_revenue'] = result['gross_revenue_eur'] - result['cancelled_revenue_eur']
result.head()

In [ ]:
# Revenue Cancellation Rate
result['revenue_cancellation_rate'] = result['cancelled_revenue_eur'] / result['gross_revenue_eur']
result['revenue_cancellation_rate'].fillna(0, inplace=True)
result.head()

In [ ]:
# Convert variables to numeric
numeric_cols = ['gross_item_eur_amount_ttv', 'cancelled_item_eur_amount_ttv']
result[numeric_cols] = result[numeric_cols].apply(pd.to_numeric)
# Fill NA values with 0 in column 'A'
result['cancelled_item_eur_amount_ttv'].fillna(0, inplace=True)
# Value >0
result = result.loc[result['gross_item_eur_amount_ttv'] >= 0]
result = result.loc[result['cancelled_item_eur_amount_ttv'] >= 0]
# Net TTV
result['net_TTV'] = result['gross_item_eur_amount_ttv'] - result['cancelled_item_eur_amount_ttv']
result.head()

In [ ]:
# Net AOV
result['net_AOV'] = result['net_TTV'] / result['net_online_orders']
result['net_AOV'].fillna(0, inplace=True)
result.head()

In [ ]:
# Net Take Rate
result['net_Take_Rate'] = result['net_revenue'] / result['net_TTV']
result['net_Take_Rate'].fillna(0, inplace=True)
result.head()

# EDA

**Variables:**
* **cancelled_item_eur_amount_ttv:** SUM(DISTINCT fct_tw_online_items.item_eur_amount) AS cancelled_item_eur_amount_TTV,
* **cancelled_aov:** cancelled_orders.cancelled_item_eur_amount_TTV/nullif(cancelled_orders.cancelled_orders,0) AS cancelled_AOV
* **cancelled_revenue_eur:** SUM(DISTINCT fct_tw_online_items.gross_revenue_eur) AS cancelled_revenue_eur
* **cancelled_take_rate:** cancelled_orders.cancelled_revenue_eur/nullif(cancelled_orders.cancelled_item_eur_amount_TTV,0) AS cancelled_take_rate

cancelled_item_eur_amount_ttv

In [ ]:
#df['cancelled_item_eur_amount_ttv'] = df['cancelled_item_eur_amount_ttv'].astype(float)
#df['cancelled_item_eur_amount_ttv'] = df['cancelled_item_eur_amount_ttv'].fillna(0)
#df['cancelled_item_eur_amount_ttv'] = df['cancelled_item_eur_amount_ttv'].astype(int)

In [ ]:
#sliced_df = df[df['cancelled_item_eur_amount_ttv'] != 0]
#sns.histplot(data=sliced_df, x="cancelled_item_eur_amount_ttv", bins=50)

In [ ]:
#sns.boxplot(data=sliced_df, x="cancelled_item_eur_amount_ttv", y="content_channel_name")

In [ ]:
#sns.boxplot(data=sliced_df, x="cancelled_item_eur_amount_ttv", y="online_order_segment")

In [ ]:
#sns.boxplot(data=sliced_df, x="cancelled_item_eur_amount_ttv", y="payment_method_name")

In [ ]:
#sns.boxplot(data=sliced_df, x="cancelled_item_eur_amount_ttv", y="saas_product")

cancelled_aov

In [ ]:
#df['cancelled_aov'] = df['cancelled_aov'].astype(float)
#df['cancelled_aov'] = df['cancelled_aov'].fillna(0)
#df['cancelled_aov'] = df['cancelled_aov'].astype(int)

In [ ]:
#col1 = df['cancelled_item_eur_amount_ttv']
#col2 = df['cancelled_aov']

In [ ]:
#sns.scatterplot(data=df, x="cancelled_aov", y="cancelled_item_eur_amount_ttv")

In [ ]:
#print("The correlation coefficient is: ", col1.corr(col2))

**Nuevas Variables**
* Finalmente utilizaremos net_TTV
* Finalmente usaremos net_AOV
* Finalmente usaremos net_Revenue y Revenue_Cancellation_Rate
* Finalmente usaremos net_Take_Rate

***Net TTV***

In [ ]:
sns.histplot(data=result, x="net_TTV", bins=50)

In [ ]:
sns.boxplot(data=result, x="net_TTV")

Analizar hasta donde permitiremos la entrada de Outliers.
**Categorizar (?)**

***Net AOV***

In [ ]:
sns.histplot(data=result, x="net_AOV", bins=50)

In [ ]:
sns.boxplot(data=result, x="net_AOV")

Analizar hasta donde permitiremos la entrada de Outliers.
**Categorizar (?)**

***Revenue Cancellation Rate***

In [ ]:
sns.histplot(data=result, x="revenue_cancellation_rate")

In [ ]:
sns.boxplot(data=result, x="revenue_cancellation_rate")

In [ ]:
result[(result['cancelled_orders'] > 0) & (result['gross_orders'] > 0)]

Dejar la variable sin trasnformar.

***Net Take Rate***

In [ ]:
sns.histplot(data=result, x="net_Take_Rate", bins=50)

In [ ]:
sns.boxplot(data=result, x="net_Take_Rate")

Estaría correcto.

# Análisis de Correlaciones

In [ ]:
col1 = result['net_AOV']
col2 = result['net_TTV']
print("The correlation coefficient is: ", col1.corr(col2))

In [ ]:
result.info()